In [1]:
#Install the necessary packages processing your data
!pip install pandas numpy 
!pip install lxml

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 123.0 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 159.6 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3
Collecting lxml
  Downloading lxml-6.1.1-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Downloading lxml-6.1.1-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 134.8 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [2]:
import numpy as np #import the numpy library to peform numerical operations with your data
import pandas as pd #import the pandas library to create your dataframes

def warn(*args,**kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [3]:
url = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29" #URL that contains our GDP data.
import requests #import the requests library so that you can retrieve data from the url. 
from bs4 import BeautifulSoup #import the BeautifulSoup library to so that you parse data from the url. 
import xml.etree.ElementTree as ET

In [4]:
#Extract the required GDP data from the given URL using Web Scraping. Extract tables from webpage using Pandas, and retain table number 3 as the required dataframe.
GDP_tables = pd.read_html(url)
GDP_df = GDP_tables[3]
print(GDP_df)

    Country/Territory UN region IMF[1][13]            World Bank[14]  \
    Country/Territory UN region   Estimate       Year       Estimate
0               World         —  105568776       2023      100562011
1       United States  Americas   26854599       2023       25462700
2               China      Asia   19373586  [n 1]2023       17963171
3               Japan      Asia    4409738       2023        4231141
4             Germany    Europe    4308854       2023        4072192
..                ...       ...        ...        ...            ...
209          Anguilla  Americas          —          —              —
210          Kiribati   Oceania        248       2023            223
211             Nauru   Oceania        151       2023            151
212        Montserrat  Americas          —          —              —
213            Tuvalu   Oceania         65       2023             60

               United Nations[15]
          Year           Estimate       Year
0         2022           96698005       2021
1         2022           23315081       2021
2    [n 3]2022           17734131  [n 1]2021
3         2022            4940878       2021
4         2022            4259935       2021
..         ...                ...        ...
209          —                303       2021
210       2022                227       2021
211       2022                155       2021
212          —                 72       2021
213       2022                 60       2021

[214 rows x 8 columns]

In [6]:
#Replace the column headers with column numbers
GDP_df2 = GDP_df.set_axis([0,1,2,3,4,5,6,7], axis ="columns")
GDP_df2

,0,1,2,3,4,5,6,7
0,World,—,105568776,2023,100562011,2022,96698005,2021
1,United States,Americas,26854599,2023,25462700,2022,23315081,2021
2,China,Asia,19373586,[n 1]2023,17963171,[n 3]2022,17734131,[n 1]2021
3,Japan,Asia,4409738,2023,4231141,2022,4940878,2021
4,Germany,Europe,4308854,2023,4072192,2022,4259935,2021
...,...,...,...,...,...,...,...,...
209,Anguilla,Americas,—,—,—,—,303,2021
210,Kiribati,Oceania,248,2023,223,2022,227,2021
211,Nauru,Oceania,151,2023,151,2022,155,2021
212,Montserrat,Americas,—,—,—,—,72,2021
213,Tuvalu,Oceania,65,2023,60,2022,60,2021

In [7]:
# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)

GDP_df3 = GDP_df2.filter(items =[0,2])
GDP_df3

                 0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
..             ...        ...
209       Anguilla          —
210       Kiribati        248
211          Nauru        151
212     Montserrat          —
213         Tuvalu         65

[214 rows x 2 columns]

In [8]:
# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
GDP_df4 = GDP_df3.iloc[1:11]
GDP_df4

                 0         2
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [13]:
# Assign column names as "Country" and "GDP (Million USD)"
GDP_df5 = GDP_df4.set_axis(['Country','GDP (Million USD)'], axis ="columns")
GDP_df5

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [28]:
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
GDP_df6 = GDP_df5.astype({'GDP (Million USD)':'int64'})
GDP_df6

           Country  GDP (Million USD)
1    United States           26854599
2            China           19373586
3            Japan            4409738
4          Germany            4308854
5            India            3736882
6   United Kingdom            3158938
7           France            2923489
8            Italy            2169745
9           Canada            2089672
10          Brazil            2081235

In [29]:
# Convert the GDP value in Million USD to Billion USD
GDP_df6['GDP (Billion USD)'] = np.round(GDP_df6['GDP (Million USD)']/1000, 2)
GDP_df6

           Country  GDP (Million USD)  GDP (Billion USD)
1    United States           26854599           26854.60
2            China           19373586           19373.59
3            Japan            4409738            4409.74
4          Germany            4308854            4308.85
5            India            3736882            3736.88
6   United Kingdom            3158938            3158.94
7           France            2923489            2923.49
8            Italy            2169745            2169.74
9           Canada            2089672            2089.67
10          Brazil            2081235            2081.24

In [34]:
# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'

GDP_df6 = GDP_df6.drop(columns=['GDP (Million USD)'])
GDP_df6

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [37]:
# Load the DataFrame to the CSV file named "Largest_economies.csv"

GDP_CSV = GDP_df6.to_csv("Largest_Economies.csv")
GDP_CSV